import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/Header/Header';

const inter = Inter({ subsets: ["latin"] });

// 기본 metadata 작성
// export const metadata: Metadata = {
//   title: "Next JS Tutorial",
//   description: "Generated by create next app",
// };

// 객체형 metadata 작성
export const metadata: Metadata = {
  title: {
    // absolute: 템플릿을 무시하는 속성
    default: 'Next JS Tutorial',
    template: '%s | Tutorial'
  },
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
